Feature Form
rodrigopenayo98/my-rod-porf pull request #3
Opened 2023-05-02 12:29 UTC by rodrigopenayo98

Added a new form section in the portfolio.

2023-05-02 16:39 UTC, bobb-Rob reviewed
Hi @rodrigopenayo98, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the contribution of your partner, kindly ensure that your partner(s) contribute to your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-05-02 18:01 UTC, rodrigopenayo98 commented
@bobb-Rob Hi! Sorry but really... I don't understand it, if you see in the repository you have 2 colaborators me and Umuhan, what do you need? She help me in one commit, you can check it in the commit history... or you need the link of the repository? I had sent you the one with the pull request with my form. Sorry but I dont understand it.

2023-05-03 10:53 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @rodrigopenayo98,

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

Indeed you did an exceptional but still, there is room for changes to complete this project. 💯


## Highlights 
☑️Well implemented design.
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.


 ## Required Changes ♻️

> **_Check the comments below to have a look at the required changes._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 10:53 UTC, ABDULALI3468 commented on index.html
>          <h2>Contact me</h2>
✅You accidently added this section as the contact form is added above already please consider removing this section entirely to meet the project requirements ✅

2023-05-03 10:53 UTC, ABDULALI3468 commented on index.html
> +            </form>
On submission of the form, it shows the following error message please consider reviewing that as the form is not even submitted.

### ERROR MESSAGE:-

![image](https://user-images.githubusercontent.com/94223367/235895060-8024cc02-2ffe-47c2-a508-d94422a86187.png)

> I request the next reviewer to again check the validations when the form is submitted 💯

2023-05-03 10:53 UTC, ABDULALI3468 commented on index.html
> +                </ul>
Please consider making the same padding inside the input elements to make the design exactly in accordance with the Figma design.

### YOUR DESIGN:-

![image](https://user-images.githubusercontent.com/94223367/235895522-927fd97c-ea05-454b-ac8e-df972d332b82.png)


### FIGMA DESIGN:-

![image](https://user-images.githubusercontent.com/94223367/235895434-66aefdde-915a-4434-9392-e7203baa31a1.png)

2023-05-03 10:53 UTC, ABDULALI3468 commented on index.html
> +          <h2>Contact me</h2>
Please consider adding the same margin-top to the section as used in the Figma design to meet the project requirements.

```
    margin-top: 176.85px;
```

2023-05-03 10:53 UTC, ABDULALI3468 commented on styles.css
> +}
Please consider using the same color as used in the Figma design to make it look alike to the design.


### Color code:-

```
.section4 p {
  color: #EBEBFF;
}
```

2023-05-03 13:06 UTC, usorfaitheloho approved these changes
Hi @rodrigopenayo98  👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/l49JNZ87F3AmPoH0A/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 13:08 UTC, merged